import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const { PDF_KNOWLEDGE } = require('./src/data/pdf-knowledge.ts');

const docRegex = /--- Start of Document: (.*?) ---\n([\s\S]*?)\n--- End of Document: \1 ---/g;

let match;
const documents: any[] = [];

while ((match = docRegex.exec(PDF_KNOWLEDGE)) !== null) {
  const filename = match[1];
  let docContent = match[2];

  // Clean up the "-- X of Y --" page number markers
  docContent = docContent.replace(/-- \d+ of \d+ --\n/g, '');
  
  // Trim excessive whitespace and newlines
  docContent = docContent.replace(/\n{3,}/g, '\n\n').trim();

  // Only keep documents that have actual content
  if (docContent.length > 0) {
    documents.push({
      filename,
      content: docContent
    });
  }
}

console.log(`Extracted ${documents.length} documents.`);

const newFileContent = `// Auto-generated by scripts/process-pdfs.ts

export interface PDFDocument {
  filename: string;
  content: string;
}

export const PDF_KNOWLEDGE: PDFDocument[] = ${JSON.stringify(documents, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'src/data/pdf-knowledge.ts'), newFileContent, 'utf-8');
console.log('Done migrating pdf-knowledge.ts');
