import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { PDFParse } from 'pdf-parse';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PDF_DIR = path.join(__dirname, '../pdfs');
const OUTPUT_FILE = path.join(__dirname, '../src/data/pdf-knowledge.ts');

async function processPdfs() {
  console.log(`Looking for PDFs in: ${PDF_DIR}`);

  if (!fs.existsSync(PDF_DIR)) {
    console.error(`Directory ${PDF_DIR} does not exist. Please create it and add your PDFs.`);
    return;
  }

  const files = fs.readdirSync(PDF_DIR).filter(file => file.toLowerCase().endsWith('.pdf'));

  if (files.length === 0) {
    console.log('No PDF files found in the pdfs directory.');
    return;
  }

  console.log(`Found ${files.length} PDF files. Starting extraction...`);

  const documents = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(PDF_DIR, file);
    try {
      console.log(`[${i + 1}/${files.length}] Processing ${file}...`);
      const dataBuffer = fs.readFileSync(filePath);
      const parser = new PDFParse({ data: dataBuffer });
      const data = await parser.getText();
      await parser.destroy();
      
      let docContent = data.text;
      
      // Clean up the "-- X of Y --" page number markers
      docContent = docContent.replace(/-- \d+ of \d+ --\n/g, '');
      
      // Trim excessive whitespace and newlines
      docContent = docContent.replace(/\n{3,}/g, '\n\n').trim();

      if (docContent.length > 0) {
        documents.push({
          filename: file,
          content: docContent
        });
      }
    } catch (error) {
      console.error(`Error processing ${file}:`, error);
    }
  }

  console.log('Finished extracting text. Writing to knowledge base file...');

  const fileContent = `// Auto-generated by scripts/process-pdfs.ts

export interface PDFDocument {
  filename: string;
  content: string;
}

export const PDF_KNOWLEDGE: PDFDocument[] = ${JSON.stringify(documents, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');

  console.log(`Successfully wrote extracted text to ${OUTPUT_FILE}`);
}

processPdfs().catch(console.error);
