import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { PDFParse } from 'pdf-parse';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PDF_DIR = path.join(__dirname, '../pdfs');
const OUTPUT_FILE = path.join(__dirname, '../src/data/pdf-knowledge.ts');

async function processPdfs() {
  console.log(`Looking for PDFs in: ${PDF_DIR}`);

  if (!fs.existsSync(PDF_DIR)) {
    console.error(`Directory ${PDF_DIR} does not exist. Please create it and add your PDFs.`);
    return;
  }

  const files = fs.readdirSync(PDF_DIR).filter(file => file.toLowerCase().endsWith('.pdf'));

  if (files.length === 0) {
    console.log('No PDF files found in the pdfs directory.');
    return;
  }

  console.log(`Found ${files.length} PDF files. Starting extraction...`);

  let combinedText = '';

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(PDF_DIR, file);
    try {
      console.log(`[${i + 1}/${files.length}] Processing ${file}...`);
      const dataBuffer = fs.readFileSync(filePath);
      const parser = new PDFParse({ data: dataBuffer });
      const data = await parser.getText();
      await parser.destroy();
      
      combinedText += `\n\n--- Start of Document: ${file} ---\n`;
      combinedText += data.text.trim();
      combinedText += `\n--- End of Document: ${file} ---\n`;
    } catch (error) {
      console.error(`Error processing ${file}:`, error);
    }
  }

  console.log('Finished extracting text. Writing to knowledge base file...');

  // Use JSON.stringify to safely escape all characters (including newlines and weird escape sequences like \9)
  const safeText = JSON.stringify(combinedText);

  const fileContent = `// Auto-generated by scripts/process-pdfs.ts\n\nexport const PDF_KNOWLEDGE = ${safeText};\n`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf-8');

  console.log(`Successfully wrote extracted text to ${OUTPUT_FILE}`);
}

processPdfs().catch(console.error);
